/*system configurations 0: off 1:on*/
#define MOVDIR64B_EMULATION 1
#define XGETBV_EMULATION 1
#define ALLOW_TDX_SINGLE_STEPPING 1
#define TURN_ON_INSTRUCTION_TRACER 0
#define DETECT_SPECIFIC_KHOLE_MAPPING 1

#define TURN_ON_MONITOR_LOGS 1
#define TURN_ON_TDXCALL_LOGS 1
#define TURN_ON_INSTRUMENTATION_LOG 0
#define TURN_ON_NP_SEAMLDR_LOGS 0
#define TURN_ON_INTERPRETER_MGR_LOGS 0

#define TDH_SERVTD_BIND_ENABLE 1
#define TD_BIND 1 /*1 bind*/
#define TD_PREBIND 2 /*2 prebind*/
#define SERVTD_BIND_TYPE TD_BIND

#define ENABLE_MKTME_CONRTOLS 0

#if TURM_ON_NP_SEAMLDR_LOGS == 1
    #define NP_SEAMLDR_LOGS_ON
#endif

#if ENABLE_MKTME_CONRTOLS == 1
    #define ENABLE_MKTME_EMULATION
#endif

#if TURN_ON_INSTRUCTION_TRACER == 1
    #define INSTRUCTION_TRACER_ON
#endif

#if TURN_ON_INSTRUMENTATION_LOG == 1
    #define INSTRUMENTATION_LOG_ON
#endif

#if XGETBV_EMULATION == 1
    #define EMULATE_XGETBV
#endif

#if MOVDIR64B_EMULATION == 1
    #define EMULATE_MOVDIR64B
#endif

#if ALLOW_TDX_SINGLE_STEPPING == 1
    #define SINGLE_STEP_TDX_MOD
#endif

#ifndef SE_START_SEAM_STATE
    // #define SE_START_SEAM_STATE SEAM_STATE_TD0_TDH_MNG_ADDCX_DONE
    #define SE_START_SEAM_STATE SEAM_STATE_TEMP
    // #define SE_START_SEAM_STATE SEAM_STATE_TDH_VP_ADDCX_DONE
#endif

#if TDH_SERVTD_BIND_ENABLE == 1
    #define ENABLE_SERVTD_BINDING
#endif

#if DETECT_SPECIFIC_KHOLE_MAPPING == 1
    #define ENABLE_DETECTTING_SPECIFIC_KEYHOLE_MAPPING
#endif