
#ifndef __X64BIN_H_
#define __X64BIN_H_

#include "platform_configs.h"
#include "configs.h"

/*For MSR*/
#define IA32_SEAMRR_BASE_MSR_ADDR                        0x1400
#define IA32_SEAMRR_MASK_MSR_ADDR                        0x1401
#define IA32_MKTME_KEYID_PARTITIONING_MSR_ADDR           0x87
#define IA32_TME_ACTIVATE_MSR_ADDR                       0x982
#define IA32_TME_CAPABILITY_MSR_ADDR                     0x981
#define IA32_SEAMEXTEND_MSR_ADDR                         0x1402
#define IA32_WBINVDP_MSR_ADDR                            0x98
#define IA32_WBNOINVDP_MSR_ADDR                          0x99

#define IA32_VMX_BASIC_MSR_ADDR                          0x480
#define IA32_VMX_CR0_FIXED0_MSR_ADDR                     0x486
#define IA32_VMX_CR0_FIXED1_MSR_ADDR                     0x487
#define IA32_VMX_CR4_FIXED0_MSR_ADDR                     0x488
#define IA32_VMX_CR4_FIXED1_MSR_ADDR                     0x489
#define IA32_VMX_TRUE_PINBASED_CTLS_MSR_ADDR             0x48D
#define IA32_VMX_TRUE_PROCBASED_CTLS_MSR_ADDR            0x48E
#define IA32_VMX_TRUE_EXIT_CTLS_MSR_ADDR                 0x48F
#define IA32_VMX_TRUE_ENTRY_CTLS_MSR_ADDR                0x490

#define IA32_SPEC_CTRL_MSR_ADDR                          0x48
#define IA32_CORE_CAPABILITIES                           0xCF
#define IA32_ARCH_CAPABILITIES                           0x10A                          
#define IA32_XAPIC_DISABLE_STATUS_MSR_ADDR               0xBD
#define IA32_MISC_PACKAGE_CTLS_MSR_ADDR                  0xBC
#define IA32_PERF_CAPABILITIES_MSR_ADDR                  0x345
#define IA32_TSC_ADJ_MSR_ADDR                            0x3B
#define IA32_MISC_ENABLES_MSR_ADDR                       0x1A0
#define IA32_DS_AREA_MSR_ADDR                            0x600
#define IA32_PRED_CMD_MSR_ADDR                           0x49
#define IA32_VMX_EPT_VPID_CAP_MSR_ADDR                   0x48C
#define IA32_INTR_PENDING_MSR_ADDR                       0x9A
#define IA32_UARCH_MISC_CTL_MSR_ADDR                     0x1B01
#define IA32_STAR_MSR_ADDR                               0xC0000081
#define IA32_LSTAR_MSR_ADDR                              0xC0000082
#define IA32_FMASK_MSR_ADDR                              0xC0000084
#define IA32_KERNEL_GS_BASE_MSR_ADDR                     0xC0000102
#define IA32_TSC_AUX_MSR_ADDR                            0xC0000103
#define IA32_XSS_MSR_ADDR                                0xDA0
#define IA32_FMASK_MSR_ADDR                              0xC0000084
#define IA32_TSX_CTRL_MSR_ADDR                           0x122

/*For CPUID*/
#define CPUID_GET_TOPOLOGY_LEAF         0x1F
#define CPUID_GET_MAX_PA_LEAF           0x80000008
#define CPUID_GET_TOPOLOGY_LEAF         0x1F
#define CPUID_DET_CACHE_PARAMS_LEAF     0x4
#define CPUID_DET_CACHE_PARAMS_SUBLEAF  0x3
#define CPUID_MAX_INPUT_VAL_LEAF        0
#define CPUID_MAX_EXTENDED_VAL_LEAF     0x80000000


#define R32_BITS                        0x00000000ffffffffUL

typedef union
{
    struct
    {
        uint32_t rsvd :14; // 0-13
        uint32_t max_num_of_lps_sharing_cache :12; // 14-25
        uint32_t rsvd1 :4;
    };
    uint32_t raw;
} cpu_cache_params_t;

/*for binary instrumentation----------------------------------------*/
#define PSEAMLDR_SPECIAL_INS_COUNT	    200UL
#define PSEAMLDR_TOTAL_INS_COUNT	    16000UL
#define PSEAMLDR_TRACE_SKIP_COUNT       20UL /*trace is not actually skipped*/

#define TDXMODULE_TOTAL_INS_COUNT	    75000UL

typedef enum {
	NO_REG_64, /*This is USED; keep this as the first elsement*/
	RAX,
	RBX,
	RCX,
	RDX,
	RDI,
	RSI,
	R8,
	R9,
	R10,
	R11,
	R12,
	R13,
	R14,
	R15,
	RBP,
	RIP,
	RSP,
	MAX_REGS_64 /*This is USED; keep this as the last elsement*/
} REGS_64;

typedef enum {
	START_INS, /*This is USED; keep this as the first element*/
	RDMSR,
	WRMSR,
	RDFSBASE, 
	RDGSBASE,
	CPUID,
	SEAMOPS,
	SEAMRET,
	VMCLEAR,
	VMREAD,
	VMWRITE,
    VMLAUNCH,
    VMRESUME,
    VMPTRLD,
	// INVLPG,
    INVEPT,
    INVVPID,
	/*INT, removing*/
	RDRAND,
    RDSEED,
    CFLUSHOPT,
    PCONFIG,
#ifdef EMULATE_XGETBV
    XGETBV,
#endif
#ifdef EMULATE_MOVDIR64B
    MOVDIR64B,
#endif
	DATA16,
	MAX_INS /*This is USED; keep this as the last element*/
} INS;


typedef union {
    struct
    {
        uint64_t
            cf         : 1,
            reserved_0 : 1, // must be 1
            pf         : 1,
            reserved_1 : 1, // must be 0
            af         : 1,
            reserved_2 : 1, // must be 0
            zf         : 1,
            sf         : 1,
            tf         : 1,
            ief        : 1,
            df         : 1,
            of         : 1,
            iopl       : 2,
            nt         : 1,
            reserved_3 : 1, // must be 0
            rf         : 1,
            vm         : 1,
            ac         : 1,
            vif        : 1,
            vip        : 1,
            id         : 1,
            reserved_4 : 42; // must be 0
    };
    uint64_t raw;
} ia32_rflags_t;

typedef enum {
    VMEXIT_REASON_EXCEPTION_OR_NMI                       = 0,
    VMEXIT_REASON_INTERRUPT                              = 1,
    VMEXIT_REASON_TRIPLE_FAULT                           = 2,
    VMEXIT_REASON_INIT_EVENT                             = 3,
    VMEXIT_REASON_SIPI_EVENT                             = 4,
    VMEXIT_REASON_SMI_IO_EVENT                           = 5,
    VMEXIT_REASON_SMI_OTHER_EVENT                        = 6,
    VMEXIT_REASON_INTERRUPT_WINDOW                       = 7,
    VMEXIT_REASON_NMI_WINDOW                             = 8,
    VMEXIT_REASON_TASK_SWITCH                            = 9,
    VMEXIT_REASON_CPUID_INSTRUCTION                      = 10,
    VMEXIT_REASON_GETSEC_INSTRUCTION                     = 11,
    VMEXIT_REASON_HLT_INSTRUCTION                        = 12,
    VMEXIT_REASON_INVD_INSTRUCTION                       = 13,
    VMEXIT_REASON_INVLPG_INSTRUCTION                     = 14,
    VMEXIT_REASON_RDPMC_INSTRUCTION                      = 15,
    VMEXIT_REASON_RDTSC_INSTRUCTION                      = 16,
    VMEXIT_REASON_RSM_INSTRUCTION                        = 17,
    VMEXIT_REASON_VMCALL_INSTRUCTION                     = 18,
    VMEXIT_REASON_VMCLEAR_INSTRUCTION                    = 19,
    VMEXIT_REASON_VMLAUNCH_INSTRUCTION                   = 20,
    VMEXIT_REASON_VMPTRLD_INSTRUCTION                    = 21,
    VMEXIT_REASON_VMPTRST_INSTRUCTION                    = 22,
    VMEXIT_REASON_VMREAD_INSTRUCTION                     = 23,
    VMEXIT_REASON_VMRESUME_INSTRUCTION                   = 24,
    VMEXIT_REASON_VMWRITE_INSTRUCTION                    = 25,
    VMEXIT_REASON_VMXOFF_INSTRUCTION                     = 26,
    VMEXIT_REASON_VMXON_INSTRUCTION                      = 27,
    VMEXIT_REASON_CR_ACCESS                              = 28,
    VMEXIT_REASON_DR_ACCESS                              = 29,
    VMEXIT_REASON_IO_INSTRUCTION                         = 30,
    VMEXIT_REASON_MSR_READ                               = 31,
    VMEXIT_REASON_MSR_WRITE                              = 32,
    VMEXIT_REASON_FAILED_VMENTER_GS                      = 33,
    VMEXIT_REASON_FAILED_VMENTER_MSR                     = 34,
    VMEXIT_REASON_VMEXIT_FAILURE                         = 35,
    VMEXIT_REASON_MWAIT_INSTRUCTION                      = 36,
    VMEXIT_REASON_MTF                                    = 37,
    VMEXIT_REASON_MONITOR_INSTRUCTION                    = 39,
    VMEXIT_REASON_PAUSE_INSTRUCTION                      = 40,
    VMEXIT_REASON_FAILED_VMENTER_MC                      = 41,
    VMEXIT_REASON_C_STATE_SMI                            = 42,
    VMEXIT_REASON_TPR_BELOW_THRESHOLD                    = 43,
    VMEXIT_REASON_APIC_ACCESS                            = 44,
    VMEXIT_REASON_VIRTUALIZED_EOI                        = 45,
    VMEXIT_REASON_GDTR_IDTR_ACCESS                       = 46,
    VMEXIT_REASON_LDTR_TR_ACCESS                         = 47,
    VMEXIT_REASON_EPT_VIOLATION                          = 48,
    VMEXIT_REASON_EPT_MISCONFIGURATION                   = 49,
    VMEXIT_REASON_INVLEPT                                = 50,
    VMEXIT_REASON_RDTSCP                                 = 51,
    VMEXIT_REASON_PREEMPTION_TIMER_EXPIRED               = 52,
    VMEXIT_REASON_INVLVPID                               = 53,
    VMEXIT_REASON_WBINVD_INSTRUCTION                     = 54,
    VMEXIT_REASON_XSETBV_INSTRUCTION                     = 55,
    VMEXIT_REASON_APIC_WRITE                             = 56,
    VMEXIT_REASON_RDRAND_INSTRUCTION                     = 57,
    VMEXIT_REASON_INVPCID_INSTRUCTION                    = 58,
    VMEXIT_REASON_VMFUNC_INSTRUCTION                     = 59,
    VMEXIT_REASON_ENCLS_INSTRUCTION                      = 60,
    VMEXIT_REASON_RDSEED_INSTRUCTION                     = 61,
    VMEXIT_REASON_EPT_PML_FULL                           = 62,
    VMEXIT_REASON_XSAVES_INSTRUCTION                     = 63,
    VMEXIT_REASON_XRSTORS_INSTRUCTION                    = 64,
    VMEXIT_REASON_PCONFIG                                = 65,
    VMEXIT_REASON_SPP_INDUCED                            = 66,
    VMEXIT_REASON_UMWAIT                                 = 67,
    VMEXIT_REASON_TPAUSE                                 = 68,
    VMEXIT_REASON_LOADIWK_INSTRUCTION                    = 69,
    VMEXIT_REASON_ENCLV_INSTRUCTION                      = 70,
    VMEXIT_REASON_SGX_CONFLICT                           = 71,
    VMEXIT_REASON_ENQCMD_PASID_TRANSLATION_FAILURE       = 72,
    VMEXIT_REASON_ENQCMDS_PASID_TRANSLATION_FAILURE      = 73,
    VMEXIT_REASON_BUS_LOCK                               = 74,
    VMEXIT_REASON_NOTIFICATION                           = 75,
    VMEXIT_REASON_SEAMCALL                               = 76,
    VMEXIT_REASON_TDCALL                                 = 77
} vm_exit_basic_reason_e;

/*vmcs fields*/
#define VMX_GUEST_ES_SELECTOR_ENCODE  0x0800ULL
#define VMX_GUEST_ES_ARBYTE_ENCODE  0x4814ULL
#define VMX_GUEST_ES_LIMIT_ENCODE  0x4800ULL
#define VMX_GUEST_ES_BASE_ENCODE  0x6806ULL
#define VMX_GUEST_CS_SELECTOR_ENCODE  0x0802ULL
#define VMX_GUEST_CS_ARBYTE_ENCODE  0x4816ULL
#define VMX_GUEST_CS_LIMIT_ENCODE  0x4802ULL
#define VMX_GUEST_CS_BASE_ENCODE  0x6808ULL
#define VMX_GUEST_SS_SELECTOR_ENCODE  0x0804ULL
#define VMX_GUEST_SS_ARBYTE_ENCODE  0x4818ULL
#define VMX_GUEST_SS_LIMIT_ENCODE  0x4804ULL
#define VMX_GUEST_SS_BASE_ENCODE  0x680AULL
#define VMX_GUEST_DS_SELECTOR_ENCODE  0x0806ULL
#define VMX_GUEST_DS_ARBYTE_ENCODE  0x481AULL
#define VMX_GUEST_DS_LIMIT_ENCODE  0x4806ULL
#define VMX_GUEST_DS_BASE_ENCODE  0x680CULL
#define VMX_GUEST_LDTR_SELECTOR_ENCODE  0x080CULL
#define VMX_GUEST_LDTR_ARBYTE_ENCODE  0x4820ULL
#define VMX_GUEST_LDTR_LIMIT_ENCODE  0x480CULL
#define VMX_GUEST_LDTR_BASE_ENCODE  0x6812ULL
#define VMX_GUEST_TR_SELECTOR_ENCODE  0x080EULL
#define VMX_GUEST_TR_ARBYTE_ENCODE  0x4822ULL
#define VMX_GUEST_TR_LIMIT_ENCODE  0x480EULL
#define VMX_GUEST_TR_BASE_ENCODE  0x6814ULL
#define VMX_GUEST_FS_SELECTOR_ENCODE  0x0808ULL
#define VMX_GUEST_FS_ARBYTE_ENCODE  0x481CULL
#define VMX_GUEST_FS_LIMIT_ENCODE  0x4808ULL
#define VMX_GUEST_FS_BASE_ENCODE  0x680EULL
#define VMX_GUEST_GS_SELECTOR_ENCODE  0x080AULL
#define VMX_GUEST_GS_ARBYTE_ENCODE  0x481EULL
#define VMX_GUEST_GS_LIMIT_ENCODE  0x480AULL
#define VMX_GUEST_GS_BASE_ENCODE  0x6810ULL
#define VMX_NOTIFY_WINDOW_ENCODE  0x4024ULL
#define VMX_GUEST_GDTR_LIMIT_ENCODE  0x4810ULL
#define VMX_GUEST_GDTR_BASE_ENCODE  0x6816ULL
#define VMX_RSVD_32_BIT_GUEST_STATE_ENCODE  0x4830ULL
#define VMX_GUEST_IDTR_LIMIT_ENCODE  0x4812ULL
#define VMX_GUEST_IDTR_BASE_ENCODE  0x6818ULL
#define VMX_HOST_ES_SELECTOR_ENCODE  0x0C00ULL
#define VMX_HOST_CS_SELECTOR_ENCODE  0x0C02ULL
#define VMX_HOST_SS_SELECTOR_ENCODE  0x0C04ULL
#define VMX_HOST_DS_SELECTOR_ENCODE  0x0C06ULL
#define VMX_HOST_FS_SELECTOR_ENCODE  0x0C08ULL
#define VMX_HOST_GS_SELECTOR_ENCODE  0x0C0AULL
#define VMX_HOST_TR_SELECTOR_ENCODE  0x0C0CULL
#define VMX_GUEST_VPID_ENCODE  0x0000ULL
#define VMX_OSV_CVP_FULL_ENCODE  0x200CULL
#define VMX_OSV_CVP_HIGH_ENCODE  0x200dULL
#define VMX_VM_INSTRUCTION_ERRORCODE_ENCODE  0x4400ULL
#define VMX_PAUSE_LOOP_EXITING_GAP_ENCODE  0x4020ULL
#define VMX_PAUSE_LOOP_EXITING_WINDOW_ENCODE  0x4022ULL
#define VMX_GUEST_SAVED_WORKING_VMCS_POINTER_FULL_ENCODE  0x2800ULL
#define VMX_GUEST_SAVED_WORKING_VMCS_POINTER_HIGH_ENCODE  0x2801ULL
#define VMX_GUEST_IA32_DEBUGCTLMSR_FULL_ENCODE  0x2802ULL
#define VMX_GUEST_IA32_DEBUGCTLMSR_HIGH_ENCODE  0x2803ULL
#define VMX_GUEST_IA32_PAT_FULL_ENCODE  0x2804ULL
#define VMX_GUEST_IA32_PAT_HIGH_ENCODE  0x2805ULL
#define VMX_GUEST_IA32_EFER_FULL_ENCODE  0x2806ULL
#define VMX_GUEST_IA32_EFER_HIGH_ENCODE  0x2807ULL
#define VMX_GUEST_IA32_PERF_GLOBAL_CONTROL_FULL_ENCODE  0x2808ULL
#define VMX_GUEST_IA32_PERF_GLOBAL_CONTROL_HIGH_ENCODE  0x2809ULL
#define VMX_VM_EXECUTION_CONTROL_PROC_BASED_ENCODE  0x4002ULL
#define VMX_VM_EXECUTION_CONTROL_SECONDARY_PROC_BASED_ENCODE  0x401EULL
#define VMX_VM_EXECUTION_CONTROL_PIN_BASED_ENCODE  0x4000ULL
#define VMX_TPR_THRESHOLD_ENCODE  0x401CULL
#define VMX_PAGEFAULT_ERRORCODE_MASK_ENCODE  0x4006ULL
#define VMX_PAGEFAULT_ERRORCODE_MATCH_ENCODE  0x4008ULL
#define VMX_GUEST_INTERRUPTIBILITY_ENCODE  0x4824ULL
#define VMX_GUEST_SLEEP_STATE_ENCODE  0x4826ULL
#define VMX_GUEST_EPT_POINTER_FULL_ENCODE  0x201AULL
#define VMX_GUEST_EPT_POINTER_HIGH_ENCODE  0x201bULL
#define VMX_GUEST_PHYSICAL_ADDRESS_INFO_FULL_ENCODE  0x2400ULL
#define VMX_GUEST_PHYSICAL_ADDRESS_INFO_HIGH_ENCODE  0x2401ULL
#define VMX_VM_ENTRY_INTR_INFO_ENCODE  0x4016ULL
#define VMX_VM_ENTRY_EXCEPTION_ERRORCODE_ENCODE  0x4018ULL
#define VMX_VM_ENTRY_INSTRUCTION_LENGTH_ENCODE  0x401AULL
#define VMX_VM_EXIT_CONTROL_ENCODE  0x400CULL
#define VMX_GUEST_PREEMPTION_TIMER_COUNT_ENCODE  0x482EULL
#define VMX_VM_EXIT_MSR_STORE_COUNT_ENCODE  0x400EULL
#define VMX_VM_EXIT_MSR_LOAD_COUNT_ENCODE  0x4010ULL
#define VMX_VM_EXIT_REASON_ENCODE  0x4402ULL
#define VMX_VM_EXIT_INTERRUPTION_INFO_ENCODE  0x4404ULL
#define VMX_VM_EXIT_EXCEPTION_ERRORCODE_ENCODE  0x4406ULL
#define VMX_VM_EXIT_IDT_VECTOR_FIELD_ENCODE  0x4408ULL
#define VMX_VM_EXIT_IDT_VECTOR_ERRORCODE_ENCODE  0x440AULL
#define VMX_VM_EXIT_INSTRUCTION_LENGTH_ENCODE  0x440CULL
#define VMX_VM_EXIT_INSTRUCTION_INFO_ENCODE  0x440EULL
#define VMX_TSC_OFFSET_FULL_ENCODE  0x2010ULL
#define VMX_TSC_OFFSET_HIGH_ENCODE  0x2011ULL
#define VMX_VM_EXIT_QUALIFICATION_ENCODE  0x6400ULL
#define VMX_VM_EXIT_IO_RCX_ENCODE  0x6402ULL
#define VMX_VM_EXIT_IO_RSI_ENCODE  0x6404ULL
#define VMX_VM_EXIT_IO_RDI_ENCODE  0x6406ULL
#define VMX_VM_EXIT_IO_RIP_ENCODE  0x6408ULL
#define VMX_VM_EXIT_GUEST_LINEAR_ADDRESS_ENCODE  0x640AULL
#define VMX_GUEST_DR7_ENCODE  0x681AULL
#define VMX_GUEST_RSP_ENCODE  0x681CULL
#define VMX_GUEST_RIP_ENCODE  0x681EULL
#define VMX_GUEST_RFLAGS_ENCODE  0x6820ULL
#define VMX_GUEST_PND_DEBUG_EXCEPTION_ENCODE  0x6822ULL
#define VMX_GUEST_IA32_SYSENTER_ESP_ENCODE  0x6824ULL
#define VMX_GUEST_IA32_SYSENTER_EIP_ENCODE  0x6826ULL
#define VMX_GUEST_IA32_SYSENTER_CS_ENCODE  0x482AULL
#define VMX_EPTP_INDEX_ENCODE  0x0004ULL
#define VMX_GUEST_CR0_ENCODE  0x6800ULL
#define VMX_GUEST_CR3_ENCODE  0x6802ULL
#define VMX_GUEST_CR4_ENCODE  0x6804ULL
#define VMX_GUEST_PDPTR0_FULL_ENCODE  0x280AULL
#define VMX_GUEST_PDPTR0_HIGH_ENCODE  0x280bULL
#define VMX_GUEST_PDPTR1_FULL_ENCODE  0x280CULL
#define VMX_GUEST_PDPTR1_HIGH_ENCODE  0x280dULL
#define VMX_GUEST_PDPTR2_FULL_ENCODE  0x280EULL
#define VMX_GUEST_PDPTR2_HIGH_ENCODE  0x280fULL
#define VMX_GUEST_PDPTR3_FULL_ENCODE  0x2810ULL
#define VMX_GUEST_PDPTR3_HIGH_ENCODE  0x2811ULL
#define VMX_CR0_GUEST_HOST_MASK_ENCODE  0x6000ULL
#define VMX_CR4_GUEST_HOST_MASK_ENCODE  0x6002ULL
#define VMX_CR0_READ_SHADOW_ENCODE  0x6004ULL
#define VMX_CR4_READ_SHADOW_ENCODE  0x6006ULL
#define VMX_CR3_TARGET_VALUE_0_ENCODE  0x6008ULL
#define VMX_CR3_TARGET_VALUE_1_ENCODE  0x600AULL
#define VMX_CR3_TARGET_VALUE_2_ENCODE  0x600CULL
#define VMX_CR3_TARGET_VALUE_3_ENCODE  0x600EULL
#define VMX_EOI_EXIT_TABLE_0_FULL_ENCODE  0x201CULL
#define VMX_EOI_EXIT_TABLE_0_HIGH_ENCODE  0x201dULL
#define VMX_EOI_EXIT_TABLE_1_FULL_ENCODE  0x201EULL
#define VMX_EOI_EXIT_TABLE_1_HIGH_ENCODE  0x201fULL
#define VMX_EOI_EXIT_TABLE_2_FULL_ENCODE  0x2020ULL
#define VMX_EOI_EXIT_TABLE_2_HIGH_ENCODE  0x2021ULL
#define VMX_EOI_EXIT_TABLE_3_FULL_ENCODE  0x2022ULL
#define VMX_EOI_EXIT_TABLE_3_HIGH_ENCODE  0x2023ULL
#define VMX_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS_FULL_ENCODE  0x2016ULL
#define VMX_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS_HIGH_ENCODE  0x2017ULL
#define VMX_GUEST_SMBASE_ENCODE  0x4828ULL
#define VMX_POSTED_INTERRUPT_NOTIFICATION_VECTOR_ENCODE  0x0002ULL
#define VMX_EXCEPTION_BITMAP_ENCODE  0x4004ULL
#define VMX_CR3_TARGET_COUNT_ENCODE  0x400AULL
#define VMX_VM_ENTRY_CONTROL_ENCODE  0x4012ULL
#define VMX_VM_ENTRY_MSR_LOAD_COUNT_ENCODE  0x4014ULL
#define VMX_VIRTUAL_APIC_PAGE_ADDRESS_FULL_ENCODE  0x2012ULL
#define VMX_VIRTUAL_APIC_PAGE_ADDRESS_HIGH_ENCODE  0x2013ULL
#define VMX_IO_BITMAP_A_PHYPTR_FULL_ENCODE  0x2000ULL
#define VMX_IO_BITMAP_A_PHYPTR_HIGH_ENCODE  0x2001ULL
#define VMX_IO_BITMAP_B_PHYPTR_FULL_ENCODE  0x2002ULL
#define VMX_IO_BITMAP_B_PHYPTR_HIGH_ENCODE  0x2003ULL
#define VMX_EXIT_MSR_STORE_PHYPTR_FULL_ENCODE  0x2006ULL
#define VMX_EXIT_MSR_STORE_PHYPTR_HIGH_ENCODE  0x2007ULL
#define VMX_EXIT_MSR_LOAD_PHYPTR_FULL_ENCODE  0x2008ULL
#define VMX_EXIT_MSR_LOAD_PHYPTR_HIGH_ENCODE  0x2009ULL
#define VMX_ENTRY_MSR_LOAD_PHYPTR_FULL_ENCODE  0x200AULL
#define VMX_ENTRY_MSR_LOAD_PHYPTR_HIGH_ENCODE  0x200bULL
#define VMX_VIRTUAL_APIC_ACCESS_PAGE_ADDRESS_FULL_ENCODE  0x2014ULL
#define VMX_VIRTUAL_APIC_ACCESS_PAGE_ADDRESS_HIGH_ENCODE  0x2015ULL
#define VMX_MSR_BITMAP_PHYPTR_FULL_ENCODE  0x2004ULL
#define VMX_MSR_BITMAP_PHYPTR_HIGH_ENCODE  0x2005ULL
#define VMX_HOST_RSP_ENCODE  0x6C14ULL
#define VMX_HOST_RIP_ENCODE  0x6C16ULL
#define VMX_HOST_IA32_PAT_FULL_ENCODE  0x2c00ULL
#define VMX_HOST_IA32_PAT_HIGH_ENCODE  0x2c01
#define VMX_HOST_IA32_EFER_FULL_ENCODE  0x2c02
#define VMX_HOST_IA32_EFER_HIGH_ENCODE  0x2c03
#define VMX_HOST_IA32_PERF_GLOBAL_CONTROL_FULL_ENCODE  0x2c04
#define VMX_HOST_IA32_PERF_GLOBAL_CONTROL_HIGH_ENCODE  0x2c05
#define VMX_HOST_CR0_ENCODE  0x6C00
#define VMX_HOST_CR3_ENCODE  0x6C02
#define VMX_HOST_CR4_ENCODE  0x6C04ULL
#define VMX_HOST_IDTR_BASE_ENCODE  0x6C0E
#define VMX_HOST_GDTR_BASE_ENCODE  0x6C0C
#define VMX_HOST_FS_BASE_ENCODE  0x6C06
#define VMX_HOST_GS_BASE_ENCODE  0x6C08
#define VMX_HOST_TR_BASE_ENCODE  0x6C0A
#define VMX_HOST_IA32_SYSENTER_ESP_ENCODE  0x6C10
#define VMX_HOST_IA32_SYSENTER_EIP_ENCODE  0x6C12
#define VMX_HOST_IA32_SYSENTER_CS_ENCODE  0x4C00
#define VMX_GUEST_INTERRUPT_STATUS_ENCODE  0x0810
#define VMX_GUEST_UINV_ENCODE  0x0814
#define VMX_PML_INDEX_ENCODE  0x0812
#define VMX_VM_FUNCTION_CONTROLS_FULL_ENCODE  0x2018
#define VMX_VM_FUNCTION_CONTROLS_HIGH_ENCODE  0x2019
#define VMX_EPTP_LIST_ADDRESS_FULL_ENCODE  0x2024
#define VMX_EPTP_LIST_ADDRESS_HIGH_ENCODE  0x2025
#define VMX_VMREAD_BITMAP_ADDRESS_FULL_ENCODE  0x2026
#define VMX_VMREAD_BITMAP_ADDRESS_HIGH_ENCODE  0x2027
#define VMX_VMWRITE_BITMAP_ADDRESS_FULL_ENCODE  0x2028
#define VMX_VMWRITE_BITMAP_ADDRESS_HIGH_ENCODE  0x2029
#define VMX_PML_LOG_ADDRESS_FULL_ENCODE  0x200E
#define VMX_PML_LOG_ADDRESS_HIGH_ENCODE  0x200f
#define VMX_XSS_EXIT_CONTROL_FULL_ENCODE  0x202C
#define VMX_XSS_EXIT_CONTROL_HIGH_ENCODE  0x202d
#define VMX_ENCLS_EXIT_CONTROL_FULL_ENCODE  0x202E
#define VMX_ENCLS_EXIT_CONTROL_HIGH_ENCODE  0x202f
#define VMX_RSVD_64_BIT_VMEXIT_DATA_FULL_ENCODE  0x2402
#define VMX_RSVD_64_BIT_VMEXIT_DATA_HIGH_ENCODE  0x2403
#define VMX_ENCLV_EXIT_CONTROL_FULL_ENCODE  0x2036
#define VMX_ENCLV_EXIT_CONTROL_HIGH_ENCODE  0x2037
#define VMX_VIRTUAL_EXCEPTION_INFO_ADDRESS_FULL_ENCODE  0x202A
#define VMX_VIRTUAL_EXCEPTION_INFO_ADDRESS_HIGH_ENCODE  0x202b
#define VMX_GUEST_BNDCFGS_FULL_ENCODE  0x2812
#define VMX_GUEST_BNDCFGS_HIGH_ENCODE  0x2813
#define VMX_SPPTP_FULL_ENCODE  0x2030
#define VMX_SPPTP_HIGH_ENCODE  0x2031
#define VMX_TSC_MULTIPLIER_FULL_ENCODE  0x2032
#define VMX_TSC_MULTIPLIER_HIGH_ENCODE  0x2033
#define VMX_GUEST_RTIT_CTL_FULL_ENCODE  0x2814
#define VMX_GUEST_RTIT_CTL_HIGH_ENCODE  0x2815
#define VMX_VM_EXECUTION_CONTROL_TERTIARY_PROC_BASED_FULL_ENCODE  0x2034
#define VMX_VM_EXECUTION_CONTROL_TERTIARY_PROC_BASED_HIGH_ENCODE  0x2035
#define VMX_PCONFIG_EXITING_FULL_ENCODE  0x203E
#define VMX_PCONFIG_EXITING_HIGH_ENCODE  0x203f
#define VMX_PASID_LOW_FULL_ENCODE  0x2038
#define VMX_PASID_LOW_HIGH_ENCODE  0x2039
#define VMX_PASID_HIGH_FULL_ENCODE  0x203A
#define VMX_PASID_HIGH_HIGH_ENCODE  0x203b
#define VMX_HOST_IA32_INTERRUPT_SSP_TABLE_ADDR_ENCODE  0x6C1C
#define VMX_GUEST_IA32_S_CET_ENCODE  0x6828
#define VMX_GUEST_SSP_ENCODE  0x682A
#define VMX_GUEST_IA32_INTERRUPT_SSP_TABLE_ADDR_ENCODE  0x682C
#define VMX_HOST_IA32_S_CET_ENCODE  0x6C18
#define VMX_HOST_SSP_ENCODE  0x6C1A
#define VMX_HKID_ENCODE  0x4026
#define VMX_GUEST_SHARED_EPT_POINTER_FULL_ENCODE  0x203C
#define VMX_GUEST_SHARED_EPT_POINTER_HIGH_ENCODE  0x203D
#define VMX_NO_COMMIT_THRESHOLD_ENCODE  0x4024
#define VMX_GUEST_LBR_CTL_FULL_ENCODE  0x2816
#define VMX_GUEST_PKRS_FULL_ENCODE  0x2818
#define VMX_HLATP_FULL_ENCODE  0x2040
#define VMX_IA32_SPEC_CTRL_MASK 0x204A
#define VMX_IA32_SPEC_CTRL_SHADOW 0x204C

#endif
