#include "user_configs.h"

#define ENABLE_MKTME_CONRTOLS 0

#if TURN_ON_SINGLE_CALL_EXEC_MODE == 1
    #define IN_SINGLE_CALL_TESTS
#endif

#if TURN_ON_SYMBOLIC_EXECUTION == 1
    #define IN_SE_MODE
#endif

#if TURN_ON_CALL_TIME_MEASUREMENT == 1
    #define MEASURE_TDXCALL_TIME
#endif

#if GET_SPECIAL_INSTRUCTIONS == 1
    #define PRINT_SPECIAL_INSTRUCTIONS
    #define INSTRUMENTATION_LOG_ON
#endif

#if TURN_ON_LOG_TRACE == 1
    #define PRINT_GENERIC_LOGS
#endif

#if TURN_ON_PATH_EXPLORATION == 1
    #define IN_PATH_EXPLORATION_MODE
#endif

#if TURM_ON_NP_SEAMLDR_LOGS == 1
    #define NP_SEAMLDR_LOGS_ON
#endif

#if ENABLE_MKTME_CONRTOLS == 1
    #define ENABLE_MKTME_EMULATION
#endif

#if TURN_ON_INSTRUCTION_TRACER == 1
    #define INSTRUCTION_TRACER_ON
#endif

#if TURN_ON_INSTRUMENTATION_LOG == 1
    #define INSTRUMENTATION_LOG_ON
#endif

#if XGETBV_EMULATION == 1
    #define EMULATE_XGETBV
#endif

#if MOVDIR64B_EMULATION == 1
    #define EMULATE_MOVDIR64B
#endif

#if ALLOW_TDX_SINGLE_STEPPING == 1
    #define SINGLE_STEP_TDX_MOD
#endif

#ifndef SE_START_SEAM_STATE
    // #define SE_START_SEAM_STATE SEAM_STATE_TD0_TDH_MNG_ADDCX_DONE
    #define SE_START_SEAM_STATE SEAM_STATE_TEMP
    // #define SE_START_SEAM_STATE SEAM_STATE_TDH_VP_ADDCX_DONE
#endif

#if TDH_SERVTD_BIND_ENABLE == 1
    #define ENABLE_SERVTD_BINDING
#endif

#if DETECT_SPECIFIC_KHOLE_MAPPING == 1
    #define ENABLE_DETECTTING_SPECIFIC_KEYHOLE_MAPPING
#endif

#if TURN_ON_MOD_INSTALL_TIME_MEASUREMENT == 1
    #define MEASURE_MOD_INSTALL_TIME_AND_STOP
#endif

#if TURN_ON_PLATFORM_INIT_TIME_MEASUREMENT == 1
    #define MEASURE_PLATFORM_INIT_TIME_AND_STOP
#endif

#if TURN_ON_TD_CREATION_TIME_MEASUREMENT == 1
    #define MEASURE_TD_BUILD_TIME_AND_STOP
#endif

#if TURN_ON_MEMORY_TEST == 1
    #define IN_MEMORY_TEST
#endif